travis:
  secure:
    BINSTAR_TOKEN: G4MXe690qw7DVy4FoCVKOt80lEM63tP4wtC1v+5xmzejiJu96cFX86jidl9U2shc5tXJPQd9jAB7D9uRa8TqMcY7Ut5HHQ/Hjn4gaa3ofCYFkSfII6e2MFaIKDfE1V2oOPB9eNJOwDFB3bYFbbUFQD/9uj/86HkilaIsNsnkGsgCqXdnBcvw4kr8Ug7v4hYPBbRRsBHxZVzsfyUtzrIetzQ54SuqDcN1E/+E1PVIFnRclyC1Kzoit5Dw8I+Zbhouium5foboLFXQ4pEfYuMZ4fbQcUVMFU+Qqo9TWhHoIy30PHArPfnno4Rz3S1nCPAsqBR5VFsmUeGxHLe7e/+y1YS+W2iYvLmNm+QZ0ANMC12DH8wj/ieXJbYkFmGBPS3n3co/xdy0T3SztYTOYDrZjoh3zfmXwfDxnHDEWyUksotdSdFyhdiXdccogNBP813m0TLT3z3bl9ASVgrwtzIT6rEsydc2Vpb7minZSbut7dhsoiuhdC/YXgrQQjW0j+7hGIZUTmoGGzckGNT0PjGUNZnRCBxkkQ9aqtpNB/MO2xaOTJAVC86Pe5DrFADQ1fIm06GdPQBojOr4guDIUEDHtIq9LKrs7pLrA+13CiCNV/SPOhuDjZ9+fvZxoIt9XNt7Aclgz06wMl06bzEDg/rd2SZpQnPED6s2VRTsXGQf6WA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
