travis:
  secure:
    BINSTAR_TOKEN: MT1gDpPA5J0MRJ6oQt7Djp3qyA9WUpgOWus/PiRAGFW3rrV/8X+UGTR/mQIN4fKIV1QQGBamiZfBZHpf1dJYM3knA4FU1j2Z5FNJD/jjTOqtJ4lWHG4PbkDO28TxO1ls1/tDCofZuMasa8RyBb+1rlC9vRcp96dmF3dm+ECHT59T2+nRUMP2p3QZnePWeMSEkhDpz6Tu22pCgxSpqB0MCBbagj1i6wNXphrFCOS5dVZ3QhiRr7RLHzK3gDi4+bQupIU5046mG6r8Wh4ZFR58WXVDATN2VjvWIg6JJpe4+iR/MFIREhgwlxWThjEC/Jnz0x8y5cbGUhO/zX82IMqk5+LXkSDjHmhTnaFsLBzWii6zwSSf3JekMF3hKb3y96CGOVYBHPPoqFLTGuhz37t5xqitZoD0d4DxZhaQvcbFJYbpNS/7onsntItuby8Lf3n4nHa2llJdPvKsvdBEQGwkocdrdloC/r5bzHZNbgYMTuL+woy+xRw32QrZCgRGj2Fj9tga2B+MWWswLOl67CMnA3HCcqKRwkYhDmhmkSQQv+6SSEbk42oyoz+Ww4LClQNzkPQNzEFyh0VDKwzEmHg8kdlIaLhj1E3GOA/lRJl+uSQf/+KlZdWeaDbpbjIfvChUfFL3TBST3jQX4xAS+eQtNotEAu6E7Y13rCMEp8BGx4A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
