travis:
  secure:
    BINSTAR_TOKEN: GfAZajetlPev7wRYOdzuPIBRfYzc2VmwofQK0fQAWFHgrB2Ed4BHF14WWHnmI95DUIQ87kZizLXGquBaIhs3A2dseMKGpXYVUL++BgpJ8qRJ63dVkEyvwxbF2hlA6cKwcrOkaAfSchs/zJ9WIDffl4PxtnZZqnxS046/lGcUyYpgpRahQGsaHJdsg6TY990O3nzRN6813e7jI3zKhFW83IZxcrvHzaWEWzoOu/KM9WgYOwEG0xdg3q3zis7auktR60CmY6fHamnAhjW8vDstFrEqJwwswgeykS3FnLfhDHLuTGeuZAaKT/BDbXusAeRcAplYjPnEJ1UpxSPP0mBl40r7uEZ0LWjbSd19hOOqR6tkCS3Qx0fJi88wEIlCh2OS4+dJa7aDiy/anDQNS8hs8N84nIMbdYGIB8hsMpiKzysHFBqwPa/tLOn0yyvLf1kN80ba85qM/LpTPsCbnDzhn/ebysHAuvcNYjD3Knk6rPR6QelnjFyv2i5tkvHz8tVeF+IAUFj8itF4bZtEpQBcswldPdb/n5brA/ZzuM/Mg1u1TuxuFHtZTSV8N/b9mbExJCQvsKoRhoNJ7I0GS1bS0GLbxc2OtmGRASv9a7Ni4Gl1D0Mcn12k/vI/jqfvkZMJy2nxJwI5oW3q8977pxaZWBV8ZloCbPvFj3Jh9TYQPOE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
